### ISSUE TITLE
Update UG Features

### ISSUE THREAD

**Issue by jxt00** [AY2122S2-CS2103T-T13-2/tp#153]
* [x] Command Parameter table (e.g. Explain `SIMPLE_NAME`)
* [x] `ClassGroup` -> "TAssist supports the following" needs to be rephrased to have a better way to put across that these `CLASS_TYPES` are allowed
* [x] Deleting entries -> indicate that the index is deleted from the original list too
* [x] Add a tip under `grade` on how it can be applied e.g. for participatio
* [x] Add warning/caution to `clear`

**Comment by Gernene** [comment]
Heads up: I technically didn't implement the "tip" since I mentioned the participation use case in the general description of the grade command. If we still deem it necessary I'll add it in!
