### ISSUE TITLE
[PE-D] `grade` can cause integer overflows in student grades

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-T13-2/tp#170]
Giving a student a grade of `2147483647` (i.e. `INT_MAX`) then incrementing the grade by one causes an integer overflow in the grade.

To reproduce:

```
grade a/1 s/all g/2147483647
grade a/1 s/all
```

Expected result: students are assigned a grade of `2147483648`, or an error is returned.

Actual result:
```
Student Alex Yeoh(E0123456) has been successfully given the grade -2147483648
Student Irfan Ibrahim(E0123460) has been successfully given the grade -2147483648
```

This bug will likely never be encountered in real life though, as most assignments are not graded on a scale of 2.14 billion, hence the low severity.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: zhongfu/ped#2

**Comment by lkldev** [comment]
To update grade to account integer overflow
