### ISSUE TITLE
[PE-D] Add C command does not give unkown command error

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T13-2/tp#173]
how to reproduce: input `add c`
expected: Unknown command or Unknown entity;
Actual: The command is treated as add class command;

![image.png](https://raw.githubusercontent.com/zunedz/ped/master/files/e4b25f92-33cb-442f-92a3-a539c05dbb31.png)

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: zunedz/ped#4

**Comment by lkldev** [comment]
add shorthand to entities
