### ISSUE TITLE
[PE-D] Some actual module names are rejected by program

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T13-2/tp#176]
Module names can contain characters deemed invalid by TAssist, such as ["YSS4211 India as a Rising Power, 1947-Present"](https://nusmods.com/modules/YSS4211/india-as-a-rising-power-1947-present).

To reproduce:
```
add module n/India as a Rising Power, 1947-Present c/YSS4211 a/22S2
```

Expected result: a module with the given name is added

Actual result: module name is rejected as invalid

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: zhongfu/ped#5

**Comment by lkldev** [comment]
update regex for module name
