### ISSUE TITLE
[PE-D] Some commands with invalid formats are used in the UG, under the section describing the  `delete` commands

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-T13-2/tp#187]
e.g.:

- `list student c\1`
- `list class \m 2`

Marked as low sev because:
- the commands technically still run (although without the intended effect, i.e. that the list is filtered)
- the rest of the sentence ("... deletes the 2nd class group in the **filtered** class group list (filtered by module index 2) in TAssist.") still holds, as the 2nd class group in the resulting list will still be deleted. (Though the class group list is technically not filtered.)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: zhongfu/ped#11

**Comment by lkldev** [comment]
Update slash to forward slash `/` and `\m 2` should be `m/2`
