### ISSUE TITLE
[PE-D] [FeatureFlaw] Inconvenience of editing current student details

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T13-2/tp#189]
## Recreation of Bug
To edit a student name, I would need to delete and add the student again.

## Expected outcome
Edit without deleting.

## Actual outcome
Delete then add the student to edit.

## Screenshots

![image.png](https://raw.githubusercontent.com/Ardentsoul/ped/main/files/d63837a8-6fb9-45fd-81e9-5b1046f161c3.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: Ardentsoul/ped#4

**Comment by lkldev** [comment]
feature suggestion, closing for now
