### ISSUE TITLE
[PE-D] [Suggestion] Grade Values and Representation

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-T13-2/tp#191]
## Suggestion
Shouldn't there be a note to the reader what are the grade values and what they represent.

## Screenshots
![image.png](https://raw.githubusercontent.com/Ardentsoul/ped/main/files/b155af94-92c4-4f64-8093-b8897649b9a3.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: Ardentsoul/ped#6

**Comment by lkldev** [comment]
Update the UG Command Parameters table to remove duplicate Grade parameter
