### ISSUE TITLE
[PE-D] Incorrect constraint in Userguide for delete assessment command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-T13-2/tp#208]
![image.png](https://raw.githubusercontent.com/zunedz/ped/master/files/76856a8e-87fb-4a9d-8bda-121f21ee3230.png)

At bullet point 2, it should be `the index refers to the index number shown in the displayed assessment list`

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: zunedz/ped#14

**Comment by lkldev** [comment]
Update delete assessment to  `displayed assessment list`

Update delete class group to  `displayed class group list`
